# Generated by Django 2.1.5 on 2019-02-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20190205_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
